<a href="https://colab.research.google.com/github/naruemonssp/multivariate/blob/main/Multivariate_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ให้นักศึกษาทำข้อสอบใน Colab Notebook นี้โดยกรอกข้อมูลของตัวเองใน cell ที่ 2 แล้วรัน cell ที่ 1 - 5 และเริ่มทำข้อสอบใน cell ที่ 6 เป็นต้นไป

โดยโจทย์คือ
1. ข้อมูลโจทย์ อยู่ใน ตัวแปร ```Data```
2. ทำ clustering แล้วทำ visualize ข้อมูลแบบ 2 มิติ
3. ลด Dimension ของข้อมูลเหลือ 2 มิติ แล้วทำ clustering แล้ว visualize ข้อมูลแบบ 2 มิติ
4. เปรียบเทียบความแตกต่างของผลข้อ 2. กับ ข้อ 3.
5. เขียน comments อธิบายทุกขั้นตอน
6. อัด video อธิบาย code ทุกๆขั้นตอนรวมถึงผลแล้วอัพลง youtube ในรูปแบบ unlist 
7. commit โดยใช้ชื่อ commit เป็น link youtube ที่อธิบาย code ในข้อ 6.

กำหนดส่งวันที่ 2 พฤษภาคม 2564 (โดยให้มากรอกวันที่ commit ครั้งสุดท้ายใน sheet: https://docs.google.com/spreadsheets/d/1_qJwLDJVtOW1HxBcf_FHVc6UT4J_SOonuR6o3EEnVzw/edit?usp=sharing ช่อง Final)

In [5]:
from sklearn.datasets import make_blobs
import random,math
import numpy as np
import pandas

In [6]:
Name = 'นฤมล ไสยโสภณ'
ID = '6230210506'

In [7]:
def DataGenerator(name,id):
    random.seed(int(id[3:6]))
    numfeat = random.randint(20,30)
    ct = random.randint(len(name)-6,len(name))
    
    X, y = make_blobs(n_samples=10000, centers=ct, n_features=numfeat , random_state=int(id[3:6]))

    print(f'{id[3:6]}:{numfeat}:{ct}')
    X_t = (X[:,1]*2)+int(id[3])
    X_t2 = (X[:,-1]*5)+int(id[4])

    DT = np.append(X,X_t.reshape([10000,1]),axis=1)
    DT = np.append(DT,X_t2.reshape([10000,1]),axis=1)
    
    return pandas.DataFrame(DT)

In [8]:
Data = DataGenerator(Name,ID)

021:22:9


In [9]:
Data

0          1         2   ...         21         22         23
0     -1.881603   9.411944 -4.342886  ...   2.143747  18.823887  12.718734
1      9.433821   8.617652  5.074457  ...  -3.973363  17.235304 -17.866816
2      0.980557  -4.642101  6.926628  ... -10.221365  -9.284201 -49.106824
3      9.838230  -6.300094 -6.253008  ...  -1.509307 -12.600188  -5.546535
4     10.540299   8.507117  1.949175  ...   5.147229  17.014233  27.736145
...         ...        ...       ...  ...        ...        ...        ...
9995  10.036314  -3.854634 -5.393116  ...   0.012386  -7.709268   2.061930
9996  -2.678474  10.180040 -3.464937  ...   0.306719  20.360080   3.533595
9997   7.823314   1.338850  5.474055  ...  -3.559978   2.677701 -15.799888
9998  10.138508  -2.805032 -3.973135  ...   1.691833  -5.610064  10.459167
9999   9.155762   7.953514  4.051087  ...  -4.384112  15.907027 -19.920560

[10000 rows x 24 columns]

เตรียมข้อมูลก่อนที่จะนำไปใช้ โดยการตัดตัวที่มี correlation กันออกไปก่อน เพื่อลดข้อมูลที่เหมือนกันออกจาก  Data

In [10]:
Data.shape ###ดูขนาดของข้อมูล Data

(10000, 24)

In [11]:
corr=np.corrcoef(Data.to_numpy().T) ###คำสั่งในการสร้างเมทริกซ์สหสัมพันธ์

In [12]:
corr.shape ###ดูขนาดของ corrcoef ของ Data

(24, 24)

In [13]:
corr ###ค่าสหสัมพันธ์ที่ได้

array([[ 1.        ,  0.10508988, -0.2116526 ,  0.29402071,  0.14366837,
         0.63936194,  0.16149901, -0.24170563,  0.43401815, -0.4028951 ,
         0.20433323, -0.46265514, -0.00848489,  0.44800965, -0.10592164,
        -0.60336114, -0.24780171, -0.33941049, -0.11798696, -0.21637978,
        -0.43600068, -0.21902398,  0.10508988, -0.21902398],
       [ 0.10508988,  1.        , -0.02721361,  0.0826152 ,  0.50937973,
         0.17855389, -0.71902122,  0.52319528, -0.16575458,  0.06344413,
        -0.19237659, -0.31934074,  0.09220603,  0.01541256,  0.41936907,
        -0.15324556, -0.48012562, -0.5312121 , -0.35444757,  0.07731445,
         0.02469446,  0.33651414,  1.        ,  0.33651414],
       [-0.2116526 , -0.02721361,  1.        , -0.17023656, -0.1720332 ,
        -0.43857908, -0.08162385, -0.13579729, -0.61411149,  0.12017693,
         0.21188154, -0.15427193, -0.06363363,  0.00580475,  0.709806  ,
         0.20915105,  0.20523298,  0.11451189,  0.68955662, -0.61317989,
  

ทำการวนลูปหาค่า correlation ที่ซ้ำกัน เพื่อนำค่าที่ซ้ำกันออก

In [14]:
###คำสั่งในการวนลูปเพื่อที่จะหาค่าว่าซ้ำกันหรือไม่ โดยหากมีการแสดงผลข้อมูลนั้นหมายความว่ามีค่าที่ซ้ำกัน
for i in range(corr.shape[0]): 
  for j in range(corr.shape[1]):
    if (i != j) and (corr[i,j] == 1.):
      print (f' row={i} column={j} corrcoef={corr[i,j]}')

 row=21 column=23 corrcoef=1.0
 row=23 column=21 corrcoef=1.0


จากการวนลูป จะเห็นได้ว่ามี correlation ที่ซ้ำกันอยู่ ดังนั้นจึงต้องทำการนำข้อมูลที่ซ้ำกันออกก่อน จึงจะนำข้อมูลไปใช้ได้

In [15]:
new_Data=Data.iloc[:,1:21]
new_Data

1         2         3   ...        18        19        20
0      9.411944 -4.342886  5.562642  ... -7.055799  6.219112  7.856466
1      8.617652  5.074457 -1.021238  ...  4.667649 -4.283802 -3.382692
2     -4.642101  6.926628 -3.966062  ...  3.296712 -6.498706  7.878489
3     -6.300094 -6.253008  6.011220  ... -6.775540  0.813157 -8.257090
4      8.507117  1.949175 -5.159566  ... -5.583312 -3.665500 -7.279665
...         ...       ...       ...  ...       ...       ...       ...
9995  -3.854634 -5.393116  5.008217  ... -7.028767  3.035921 -6.023779
9996  10.180040 -3.464937  3.733505  ... -8.668677  7.313801  9.668899
9997   1.338850  5.474055  5.741563  ...  2.655021 -4.640828  3.455193
9998  -2.805032 -3.973135  6.524387  ... -7.342523  1.009807 -6.344602
9999   7.953514  4.051087 -1.097649  ...  6.274257 -4.679968 -3.228370

[10000 rows x 20 columns]

In [16]:
new_Data.shape ###ดูขนาดของข้อมูลเมื่อทำการลบข้อมูลที่ซ้ำกันออก

(10000, 20)

### 2.ทำ clustering แล้วทำ visualize ข้อมูลแบบ 2 มิติ

**Clustering**


**K-mean**

***import***

In [17]:
from sklearn.cluster import KMeans 
###ทำการ import function ที่จะใช้ในการหาค่า KMean จาก sklearn.cluster

***define***

In [18]:
kmeans=KMeans(n_clusters=3,random_state=2021)
###ทำการหาค่า KMeans โดยกำหนดค่า k ที่เราต้องการ ซึ่งในการกำหนดค่า k นั้นไม่จำเป็นต้องกำหนดก็ได้ เนื่องจาก kmean มี defult
###การกำหนด random_state นั้น เพื่อที่จะให้มีการสุ่มที่จุดเดียวกัน เพื่อที่จะได้จัดกลุ่มได้เหมือนกัน

***fit-transform***

คำนวณหาจุด cluster center ของข้อมูล data ด้วยวิธี K-Means Clustering

In [21]:
kmeans.fit(new_Data)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=2021, tol=0.0001, verbose=0)

แสดง จุด cluster centers ที่คำนวณออกมาได้

In [22]:
kmeans.cluster_centers_ ###คำนวณจุด cluster centers ของข้อมูลด้วย kmeans

array([[ 1.00382174,  5.8564845 , -0.23547486,  0.50583852, -1.28128177,
        -2.09281694, -0.56181867, -2.86741666,  2.92063869, -3.09487818,
         0.36238506, -0.61807739,  0.15866298,  3.93221222, -3.00076159,
         5.5868503 ,  6.0751735 ,  2.82176252, -4.11678063,  3.36795556],
       [ 0.90219203,  1.23772891,  1.03113279, -5.93269076, -1.87548217,
         2.59355254, -3.68498377, -0.53656174, -8.74851961, -1.11115071,
         0.41097352,  5.00577572, -1.41996145, -0.46767468, -6.1236304 ,
        -2.91274698, -2.10551335, -3.53498306, -1.0379784 , -5.0613337 ],
       [ 8.89601659, -3.63089834,  5.49357184,  9.48389211,  4.0215698 ,
        -3.90561985,  9.40234659, -2.11975229,  9.06392992, -7.44470325,
         8.71282335,  5.18423077, -9.06200509,  3.2769293 , -5.48475961,
         0.39444928,  0.16804633, -7.8483737 ,  6.29081681,  9.2775513 ]])

ทำสอบการจัดกลุ่มของ Data

In [23]:
y=kmeans.predict(new_Data) ###ทำการกำหนดข้อมูลที่จัดกลุ่มเป็น y
y

array([2, 0, 0, ..., 0, 1, 0], dtype=int32)

**Visualize**

ทำ PCA ข้อมูล Data เพื่อลด Dimension

In [24]:
from sklearn.decomposition import PCA

In [25]:
pca=PCA(n_components=2) ###กำหนด Dimension=2

In [26]:
new_pca=pca.fit_transform(new_Data)

In [27]:
import matplotlib ###ทำการ import matplotlib เพื่อใช้ในการสร้างกราฟ

In [30]:
matplotlib.rcParams['figure.figsize']=[5,10]
###ทำการเพิ่มขนาดของกราฟ เพื่อให้สามารถดูการกระจายของข้อมูลได้ง่ายขึ้นในการดูข้อมูลที่ซ้อนทับกันมากๆ 

In [31]:
kmeans=KMeans(random_state=2021)
kmeans.fit(new_Data)
y=kmeans.predict(new_Data)
plt.scatter(new_pca[:,0],new_pca[:,1],c=y,alpha=0.5)

NameError: ignored

#####**นี้คือกราฟที่เรา plot ได้จากการทำ Kmean**

In [ ]:
plt.scatter(new_pca[:,0],new_pca[:,1],c=y) # cluster center
plt.plot(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],'or')

#####**กราฟนี้จะแสดง  cluster center เราจะเห็นได้ว่าจุดศูนย์กลางของกราฟ  cluster center คือจุดที่เป็นสีแดงๆ**

### จากนั้นจะทำการหาค่า k  ที่เหมาะสม โดยการใช้  Elbow Method 

**SSE**

SSE คือ sum of squared error เป็นการคำนวณหาค่าความคลาดเคลื่อน

In [ ]:
kmeans.inertia_ ###คำสั่งในการคำนวณค่า SSE ของ data

In [ ]:
SSE=list()
for k in [1,2,3,4,5,6,7,8]:
  kmeans=KMeans(n_clusters=k,random_state=2021)
  kmeans.fit(new_Data)
  SSE.append(kmeans.inertia_)

In [ ]:
SSE

In [ ]:
###ทำการนำค่า SSE ที่ได้มาทำการ plot กราฟเพื่อดูว่ามีค่า k กี่กลุ่ม
plt.plot([1,2,3,4,5,6,7,8],SSE,'o-b')
plt.xlabel('k')
plt.ylabel('SSE');

จากกราฟข้างต้นจะเห็นได้ว่า k มีทั้งหมด 3 กลุ่ม ซึ่งดูจากจุดที่ 1 และ 2 ที่มีระยะห่างระหว่างกันอย่างเห้นได้ชัด และที่จุด 3และ 4 ที่มีระยะห่างใกล้เคียงกันแต่ก็มีระยะห่างออกจากจุด 5,6,7 ที่มีระยะใกล้เคียงกัน

In [ ]:
kmeans=KMeans(n_clusters=3,random_state=2021)
kmeans.fit(new_Data)
y=kmeans.predict(new_Data)
plt.scatter(new_pca[:,0],new_pca[:,1],c=y,alpha=0.5)
plt.title('DataGenerator')
plt.xlabel('X')
plt.ylabel('Y')

จากกราฟข้างต้นจะเห็นได้ว่า เมื่อจัดกลุ่ม k ให้เท่ากับ 3 กลุ่ม ซึ่งจะมีข้อมูลอยู่ในกลุ่มเดียวกันจะอยู่ใกล้เคียงกัน และแต่ละกลุ่มแต่ละกลุ่มอยู่ระหว่างกันนั้นข้อมูลนั้นไม่ซ้อนทับกันอย่างเห็นได้ชัดเจน

**Silhouette coeffient**

การหาค่า k จากวิธี Silhouette coeffient (ค่าสัมประสิทธ์ภาพเงา)

จุดของข้อมูลนั้นอยู่ใกล้กับจุดอื่นๆ ใน cluster มากน้อยเพียงใด

จุดของข้อมูลอยู่ห่างจากจุดใน cluster อื่นมากเพียงใด

In [ ]:
from sklearn import metrics

In [ ]:
SilH=list()
for k in [2,3,4,5,6,7,8]:
  kmeans=KMeans(n_clusters=k,random_state=2021)
  kmeans.fit(new_Data)
  score=metrics.silhouette_score(Data,kmeans.labels_)
  SilH.append(score)

In [ ]:
plt.plot([2,3,4,5,6,7,8],SilH,'o-g') # ทำการ Silhouette ดีที่สุดที่ คือ 2
plt.xlabel('k')
plt.ylabel('Silhouette Score');

จากกราฟข้างต้นจะเห็นได้ว่า k มีทั้งหมด 3 กลุ่ม ซึ่งดูจากจุดที่มีระยะห่างแตกต่างกันใน 3 ช่วง โดยช่วงที่ k เท่ากับ 3,5,7

In [ ]:
matplotlib.rcParams['figure.figsize']=[10,15]

In [ ]:
kmeans=KMeans(n_clusters=3,random_state=2021)
kmeans.fit(new_Data)
y=kmeans.predict(new_Data)
plt.scatter(new_pca[:,0],new_pca[:,1],c=y,alpha=0.5)
plt.title('DataGenerator')
plt.xlabel('X')
plt.ylabel('Y')

จากกราฟข้างต้นจะเห็นได้ว่า เมื่อจัดกลุ่ม k ให้เท่ากับ 3 กลุ่ม ซึ่งจะมีข้อมูลอยู่ในกลุ่มเดียวกันจะอยู่ใกล้เคียงกัน และแต่ละกลุ่มแต่ละกลุ่มอยู่ระหว่างกันนั้นข้อมูลนั้นไม่ซ้อนทับกันอย่างเห็นได้ชัดเจน

### **3. ลด Dimension ของข้อมูลเหลือ 2 มิติ แล้วทำ clustering แล้ว visualize ข้อมูลแบบ 2 มิติ**

ใช้วิธี MDS (Multidimension Scaling) คือ การลดขนาดของตัวเเปร จากที่มีเยอะให้เหลือน้อยๆ

In [ ]:
from sklearn.manifold import MDS

In [ ]:
mds = MDS(n_components=2)

In [ ]:
new_mds = mds.fit_transform(new_Data) #ใช้คำสั่ง new data ในการตัดข้อมูลออก เพราะจะให้เกิดการ error ของข้อมูลได้เนื่องข้อมูลมีเยอะจนเกินไป

In [ ]:
kmeans_2 = KMeans(n_clusters=3,random_state=2021)
kmeans_2.fit(new_data)
g = kmeans_2.predict(new_data)

In [ ]:
plt.scatter(new_mds[:,0],new_mds[:,1],c=g,alpha=0.7)
plt.title('DataGenerator') 
plt.xlabel('X') 
plt.ylabel('Y');

#####**การเปรียบเทียบ ระหว่าง ข้อ 2 และข้อ 3 หลังจากการลด Dimension ของข้อมูลด้วย MDS**
#####**โดยพบว่าข้อมูลมีการกระจายที่ไม่แตกต่างกันของข้อที่ 2 และข้อที่ 3 สังเกตจากการกระจายของจุดสีในกราฟที่ plot ทั้งข้อที่ 2 และข้อที่ 3**